/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example;

import jakarta.persistence.EntityManager;
import jakarta.persistence.Persistence;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.testcontainers.containers.PostgreSQLContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;

import static java.util.Collections.emptyList;
import static org.assertj.core.api.Assertions.assertThat;

@Testcontainers
class AppTest {

    public EntityManager em;

    @Container
    private PostgreSQLContainer postgreSQLContainer = new PostgreSQLContainer("postgres:15")
            .withDatabaseName("db")
            .withUsername("user")
            .withPassword("password");

    @BeforeEach
    public void before() {
        System.setProperty("db.port", postgreSQLContainer.getFirstMappedPort().toString());
        var emf = Persistence.createEntityManagerFactory("pu");
        em = emf.createEntityManager();
    }

    @Test
    public void testEmptyParamList() {
        var query = em.createQuery(
                "from User u " +
                        "where COALESCE(:departments) is null or u.department in (:departments)",
                User.class);
        query.setParameter("departments", emptyList());
        var result = query.getResultList();

        assertThat(result).hasSize(2);
    }
}
